from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('load-more/', views.project_load_more, name='project_load_more'),
    path('teams/', views.team_list, name='team_list'),
    path('teams/create/', views.team_create, name='team_create'),
    path('teams/invitations/', views.team_invitations, name='team_invitations'),
    path('teams/invitations/<int:invitation_id>/respond/', views.team_invitation_respond, name='team_invitation_respond'),
    path('teams/invitations/<int:invitation_id>/cancel/', views.team_invitation_cancel, name='team_invitation_cancel'),
    path('teams/<slug:slug>/', views.team_detail, name='team_detail'),
    path('teams/<slug:slug>/invite/', views.team_invite, name='team_invite'),
    path(
        'teams/<slug:slug>/members/<int:membership_id>/role/',
        views.team_membership_role_update,
        name='team_membership_role_update',
    ),
    path('teams/<slug:slug>/roles/add/', views.team_open_role_add, name='team_open_role_add'),
    path('teams/<slug:slug>/disband/', views.team_disband, name='team_disband'),
    path('requests/', views.request_list, name='request_list'),
    path('requests/create/', views.request_create, name='request_create'),
    path('requests/<int:request_id>/', views.request_detail, name='request_detail'),
    path('requests/<int:request_id>/edit/', views.request_edit, name='request_edit'),
    path('requests/<int:request_id>/delete/', views.request_delete, name='request_delete'),
    path('requests/<int:request_id>/apply/', views.request_apply, name='request_apply'),
    path('requests/<int:request_id>/applications/', views.request_applications, name='request_applications'),
    path('applications/<int:application_id>/withdraw/', views.request_application_withdraw, name='request_application_withdraw'),
    path('applications/<int:application_id>/accept/', views.request_application_accept, name='request_application_accept'),
    path('applications/<int:application_id>/reject/', views.request_application_reject, name='request_application_reject'),
    path('saved/', views.saved_projects, name='saved_projects'),
    path('create/', views.project_create, name='project_create'),
    path('team-search/', views.team_member_search, name='team_member_search'),
    path('p/<slug:slug>/', views.project_detail_by_slug, name='project_public_detail'),
    path('<int:project_id>/out/<str:destination>/', views.project_external_redirect, name='project_external_redirect'),
    path('<int:project_id>/save/', views.toggle_project_save, name='toggle_project_save'),
    path('<int:project_id>/showcase/', views.project_showcase_manage, name='project_showcase_manage'),
    path('<int:project_id>/showcase/ai-writing/', views.project_writing_generate, name='project_writing_generate'),
    path('showcase/ai-writing/<int:suggestion_id>/apply/', views.project_writing_apply, name='project_writing_apply'),
    path('showcase/ai-writing/<int:suggestion_id>/reject/', views.project_writing_reject, name='project_writing_reject'),
    path('<int:project_id>/matches/', views.project_matches, name='project_matches'),
    path('<int:project_id>/showcase/media/add/', views.project_media_add, name='project_media_add'),
    path('<int:project_id>/showcase/repository/save/', views.project_repository_save, name='project_repository_save'),
    path('<int:project_id>/showcase/repository/delete/', views.project_repository_delete, name='project_repository_delete'),
    path('showcase/media/<int:media_id>/delete/', views.project_media_delete, name='project_media_delete'),
    path('media/<int:media_id>/<str:disposition>/', views.project_media_file, name='project_media_file'),
    path('<int:project_id>/showcase/images/add/', views.project_images_add, name='project_images_add'),
    path('showcase/media/<int:media_id>/cover/', views.project_media_set_cover, name='project_media_set_cover'),
    path('<int:project_id>/like/', views.toggle_project_like, name='toggle_project_like'),
    path('<int:project_id>/feature/', views.project_feature_toggle, name='project_feature_toggle'),
    path('<int:project_id>/showcase/contributions/add/', views.project_contribution_add, name='project_contribution_add'),
    path('showcase/contributions/<int:contribution_id>/verify/', views.project_contribution_verify, name='project_contribution_verify'),
    path('showcase/contributions/<int:contribution_id>/delete/', views.project_contribution_delete, name='project_contribution_delete'),
    path('<int:project_id>/showcase/achievements/add/', views.project_achievement_add, name='project_achievement_add'),
    path('showcase/achievements/<int:achievement_id>/delete/', views.project_achievement_delete, name='project_achievement_delete'),
    path('<int:project_id>/', views.project_detail, name='project_detail'),
    path('<int:project_id>/update/', views.project_update, name='project_update'),
    path('<int:project_id>/delete/', views.project_delete, name='project_delete'),
    path('<int:project_id>/add-update/', views.add_project_update, name='add_project_update'),
    path('<int:project_id>/add-comment/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    # Approval flow URLs
    path('<int:project_id>/approve/', views.approve_project, name='approve_project'),
    path('<int:project_id>/feedback/', views.send_feedback, name='send_feedback'),
    path('<int:project_id>/feedback/get/', views.get_feedback, name='get_feedback'),
    path('<int:project_id>/start/', views.start_project, name='start_project'),
    path('<int:project_id>/complete/', views.complete_project, name='complete_project'),
    path('<int:project_id>/change-status/', views.change_project_status, name='change_project_status'),
]
