# Generated by Django 5.2.1 on 2026-03-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltag',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_tags', to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='skilltag',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_tags', to='projects.technology'),
        ),
    ]
