# Generated by Django 5.2.1 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_show_in_alumni_list',
            field=models.BooleanField(default=True),
        ),
    ]
