# Generated by Django 5.2.1 on 2026-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_skilltag_project_links'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='skills',
        ),
        migrations.AddField(
            model_name='alumni',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='alumni_members', to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='alumni_members', to='projects.technology'),
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
    ]
