# Generated by Django 5.2.1 on 2026-01-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_tag_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Tag',
                'verbose_name_plural': 'Skill Tags',
            },
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='tags',
            field=models.ManyToManyField(related_name='old_alumni', to='alumni.tag'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(blank=True, default=2026, null=True)),
                ('current_position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid_level', 'Mid-Level'), ('senior', 'Senior')], max_length=15)),
                ('bio', models.TextField()),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('is_available_for_mentoring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_show_in_alumni_list', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='alumni', to='alumni.skilltag')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='alumni.alumni')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
