# Generated by Django 5.2.1 on 2026-04-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumni_full_name_alumni_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlumniExperience',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='AlumniProfile',
        ),
    ]
