# Generated by Django 5.2.1 on 2026-08-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_remove_alumniprofile_tags_remove_alumniprofile_user_and_more'),
        ('projects', '0021_remove_projectcasestudy_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('student_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'İnceleme bekliyor'), ('approved_linked', 'Mevcut mezuna bağlandı'), ('approved_new', 'Yeni mezun olarak onaylandı'), ('rejected', 'Reddedildi')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=32)),
                ('moderation_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alumni',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='alumni',
            constraint=models.UniqueConstraint(condition=models.Q(('student_number__isnull', False), models.Q(('student_number', ''), _negated=True)), fields=('student_number',), name='unique_nonempty_alumni_student_number'),
        ),
        migrations.AddField(
            model_name='alumniregistrationrequest',
            name='matched_alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='alumniregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_alumni_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumniregistrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alumni_registration_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='alumniregistrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='one_pending_alumni_request_per_email'),
        ),
    ]
