# Generated by Django 5.2.1 on 2026-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public projects are visible to all students'),
        ),
    ]
