# Generated by Django 5.2.1 on 2026-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private projects are only visible to team members, advisors, and assigned students'),
        ),
    ]
