# Generated by Django 5.2.1 on 2026-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_is_private_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
