# Generated by Django 5.2.1 on 2025-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_request_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respons',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='draft', max_length=20),
        ),
    ]
