# Generated by Django 5.2.1 on 2026-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='duration',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='project_requests', to='projects.projectcategory', verbose_name='Kategoriler'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Son Başvuru Tarihi'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Gerekli Koşullar'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='semester',
            field=models.CharField(blank=True, choices=[('fall', 'Güz'), ('spring', 'Bahar'), ('summer', 'Yaz')], max_length=10, null=True, verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('closed', 'Kapandı'), ('completed', 'Tamamlandı')], default='active', max_length=15, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='project_requests', to='projects.technology', verbose_name='Teknolojiler'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yıl'),
        ),
    ]
