# Generated by Django 5.2.1 on 2026-04-02 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectrequest_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='supervision_type',
            field=models.CharField(choices=[('unsupervised', 'Denetimsiz'), ('supervised', 'Denetimli')], default='unsupervised', max_length=15, verbose_name='Denetim Türü'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('in_review', 'Değerlendirme Aşamasında'), ('approved', 'Fikir Onaylandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Geri Bildirim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Feedback',
                'verbose_name_plural': 'Project Feedbacks',
            },
        ),
    ]
