# Generated by Django 5.2.1 on 2025-12-06 16:53

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    ProjectCategory = apps.get_model('projects', 'ProjectCategory')
    
    categories = [
        {'name': 'Web Uygulaması', 'color': '#3B82F6'},
        {'name': 'Mobil Uygulama', 'color': '#10B981'},
        {'name': 'Masaüstü Uygulama', 'color': '#F59E0B'},
        {'name': 'Veri Analizi', 'color': '#8B5CF6'},
        {'name': 'Yapay Zeka', 'color': '#EF4444'},
        {'name': 'Oyun Geliştirme', 'color': '#EC4899'},
        {'name': 'Gömülü Sistem', 'color': '#6B7280'},
    ]
    
    for cat_data in categories:
        ProjectCategory.objects.get_or_create(**cat_data)


def create_initial_technologies(apps, schema_editor):
    Technology = apps.get_model('projects', 'Technology')
    
    technologies = [
        {'name': 'Python', 'icon': 'fab fa-python'},
        {'name': 'JavaScript', 'icon': 'fab fa-js'},
        {'name': 'React', 'icon': 'fab fa-react'},
        {'name': 'Django', 'icon': ''},
        {'name': 'Node.js', 'icon': 'fab fa-node'},
        {'name': 'Java', 'icon': 'fab fa-java'},
        {'name': 'C++', 'icon': ''},
        {'name': 'HTML/CSS', 'icon': 'fab fa-html5'},
        {'name': 'PostgreSQL', 'icon': ''},
        {'name': 'MongoDB', 'icon': ''},
        {'name': 'Docker', 'icon': 'fab fa-docker'},
        {'name': 'Git', 'icon': 'fab fa-git-alt'},
        {'name': 'Vue.js', 'icon': 'fab fa-vuejs'},
        {'name': 'Angular', 'icon': 'fab fa-angular'},
        {'name': 'Flutter', 'icon': ''},
        {'name': 'Swift', 'icon': 'fab fa-swift'},
        {'name': 'TensorFlow', 'icon': ''},
        {'name': 'PyTorch', 'icon': ''},
    ]
    
    for tech_data in technologies:
        Technology.objects.get_or_create(**tech_data)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectcategory_technology_respons_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
        migrations.RunPython(create_initial_technologies),
    ]
