# Generated by Django 5.2.1 on 2026-04-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectrequest_supervision_type_alter_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='request',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='team',
        ),
        migrations.RemoveField(
            model_name='respons',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='responsupdate',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='responsupdate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Respons',
        ),
        migrations.DeleteModel(
            name='ResponsUpdate',
        ),
    ]
