# Generated by Django 5.2.1 on 2026-08-13 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_request_teacher_remove_respons_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('program_type', models.CharField(choices=[('support', 'Destek Programı'), ('competition', 'Yarışma'), ('hackathon', 'Hackathon'), ('incubation', 'Kuluçka Programı'), ('grant', 'Hibe Programı'), ('other', 'Diğer')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('revision_requested', 'Revizyon İstendi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_source',
            field=models.CharField(choices=[('STUDENT_IDEA', 'Öğrenci Fikri'), ('ACADEMIC_REQUEST', 'Akademisyen İlanı'), ('COURSE_ASSIGNMENT', 'Ders Kapsamında Verilen Görev'), ('DEPARTMENT_COMMUNITY', 'Bölüm veya Topluluk İhtiyacı'), ('COMPANY_ORGANIZATION', 'Şirket veya Kurum Talebi'), ('EXTERNAL_CALL', 'Yarışma veya Dış Çağrı'), ('LEGACY', 'Eski Sistem Kaydı')], default='STUDENT_IDEA', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='development_status',
            field=models.CharField(choices=[('idea', 'Fikir'), ('planning', 'Planlama'), ('in_progress', 'Geliştiriliyor'), ('on_hold', 'Beklemede'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='idea', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Gizli'), ('unlisted', 'Bağlantıya Özel'), ('public', 'Herkese Açık'), ('archived', 'Arşivlendi')], default='private', max_length=12),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='created_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_request', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tahmini Süre'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='expected_output',
            field=models.TextField(blank=True, verbose_name='Beklenen Çıktı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('open', 'Başvuruya Açık'), ('reviewing', 'Değerlendiriliyor'), ('student_selected', 'Öğrenci Seçildi'), ('closed', 'Kapandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='ProjectProgramParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('application_status', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('award', models.CharField(blank=True, max_length=200)),
                ('external_url', models.URLField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='projects.projectprogram')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('proposed_approach', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi')], default='pending', max_length=12)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.projectrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_request_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('requires_advisor', models.BooleanField(default=False)),
                ('requires_course', models.BooleanField(default=False)),
                ('requires_organization', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='projtype_active_sort_idx')],
            },
        ),
        migrations.AddField(
            model_name='projectprogram',
            name='project_types',
            field=models.ManyToManyField(blank=True, related_name='programs', to='projects.projecttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='projects.projecttype'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', 'development_status'], name='project_visibility_dev_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'creation_source'], name='project_type_source_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['approval_status', '-created_at'], name='project_approval_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['status', 'deadline'], name='request_status_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectprogramparticipation',
            constraint=models.UniqueConstraint(fields=('project', 'program'), name='unique_project_program'),
        ),
        migrations.AddIndex(
            model_name='projectrequestapplication',
            index=models.Index(fields=['project_request', 'status'], name='request_app_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectrequestapplication',
            constraint=models.UniqueConstraint(fields=('project_request', 'student'), name='unique_student_request_application'),
        ),
    ]
