# Generated by Django 5.2.1 on 2025-12-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_populate_initial_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsupdate',
            old_name='which_respons',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='responsupdate',
            name='notify_teacher',
        ),
        migrations.RemoveField(
            model_name='responsupdate',
            name='when',
        ),
    ]
