# Generated by Django 5.2.1 on 2025-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_which_respons_responsupdate_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respons',
            name='status',
        ),
        migrations.RemoveField(
            model_name='responsupdate',
            name='project_status',
        ),
        migrations.AddField(
            model_name='responsupdate',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('completed', 'Tamamlandı')], default='draft', max_length=20),
        ),
    ]
