# Generated by Django 5.2.1 on 2025-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_respons_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsupdate',
            name='status',
        ),
        migrations.AddField(
            model_name='respons',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('completed', 'Tamamlandı')], default='draft', max_length=20),
        ),
    ]
