# Generated by Django 5.2.1 on 2026-08-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectachievement_projectcasestudy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_periods', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='feature_active_dates_idx')],
            },
        ),
    ]
