# Generated by Django 5.2.1 on 2025-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_responsupdate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#10B981', help_text='Hex renk kodu', max_length=7),
        ),
    ]
