# Generated by Django 5.2.1 on 2026-08-13 14:11

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectachievement',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='projects/achievements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), projects.models.validate_project_upload_size, projects.models.validate_project_upload_content]),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(blank=True, upload_to='projects/media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf', 'mp4', 'webm']), projects.models.validate_project_upload_size, projects.models.validate_project_upload_content]),
        ),
    ]
