# Generated by Django 5.2.1 on 2026-01-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_migrate_to_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('completed', 'Tamamlandı')], default='draft', max_length=20),
        ),
    ]
