# Generated by Django 5.2.1 on 2026-08-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectrepository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcasestudy',
            name='future_developments',
            field=models.TextField(blank=True, verbose_name='Gelecek Geliştirmeler'),
        ),
        migrations.CreateModel(
            name='ProjectWritingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('suggested_fields', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('preview', 'Ön izlemede'), ('applied', 'Uygulandı'), ('rejected', 'Reddedildi')], default='preview', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_writing_suggestions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_suggestions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', '-created_at'], name='writing_project_status_idx')],
            },
        ),
    ]
