# Generated by Django 5.2.1 on 2026-08-13 16:48

from django.db import migrations, models
from django.utils.text import slugify


def populate_taxonomy_slugs(apps, schema_editor):
    for model_name, prefix in [('ProjectCategory', 'kategori'), ('Technology', 'teknoloji')]:
        Model = apps.get_model('projects', model_name)
        used = set(Model.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))
        for item in Model.objects.filter(models.Q(slug__isnull=True) | models.Q(slug='')).order_by('pk').iterator():
            base = slugify(item.name.strip()) or f'{prefix}-{item.pk}'
            candidate = base
            counter = 2
            while candidate in used:
                candidate = f'{base}-{counter}'
                counter += 1
            item.slug = candidate
            item.save(update_fields=['slug'])
            used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectcasestudy_future_developments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['group', 'sort_order', 'name'], 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technology',
            name='group',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobil'), ('ai_ml', 'Yapay zekâ ve makine öğrenmesi'), ('data_science', 'Veri bilimi'), ('database', 'Veritabanı'), ('devops', 'DevOps'), ('cloud', 'Bulut'), ('game', 'Oyun geliştirme'), ('cybersecurity', 'Siber güvenlik'), ('iot', 'IoT ve gömülü sistemler'), ('robotics', 'Robotik'), ('design', 'Tasarım ve prototipleme'), ('testing', 'Test araçları'), ('other', 'Diğer')], default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='official_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(populate_taxonomy_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
