# Generated by Django 5.2.1 on 2026-08-20 16:45

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models
from urllib.parse import urlparse
import re


REPO_PART_RE = re.compile(r'^[A-Za-z0-9_.-]+$')


def _repository_path(value):
    value = (value or '').strip()
    if not value:
        return ''
    parsed = urlparse(value)
    if parsed.scheme:
        if parsed.scheme != 'https' or parsed.hostname not in {'github.com', 'www.github.com'}:
            return None
        parts = [part for part in parsed.path.strip('/').split('/') if part]
    else:
        parts = [part for part in value.strip('/').split('/') if part]
    if len(parts) != 2:
        return None
    owner, name = parts
    if name.endswith('.git'):
        name = name[:-4]
    if not REPO_PART_RE.fullmatch(owner) or not REPO_PART_RE.fullmatch(name):
        return None
    return f'{owner}/{name}'


def preserve_repository_and_updates(apps, schema_editor):
    ProjectRepository = apps.get_model('projects', 'ProjectRepository')
    ProjectCaseStudy = apps.get_model('projects', 'ProjectCaseStudy')
    ProjectUpdate = apps.get_model('projects', 'ProjectUpdate')
    invalid = []
    for repository in ProjectRepository.objects.all().iterator():
        path = _repository_path(f'{repository.owner}/{repository.name}') or _repository_path(repository.repository_url)
        if not path:
            invalid.append(f'ProjectRepository#{repository.pk}')
            continue
        repository.repository_path = path
        repository.save(update_fields=['repository_path'])
    for case_study in ProjectCaseStudy.objects.exclude(github_url='').iterator():
        path = _repository_path(case_study.github_url)
        if not path:
            invalid.append(f'ProjectCaseStudy#{case_study.pk}')
            continue
        repository = ProjectRepository.objects.filter(project_id=case_study.project_id).first()
        if repository and repository.repository_path != path:
            invalid.append(f'ProjectCaseStudy#{case_study.pk}:conflict')
        elif repository is None:
            ProjectRepository.objects.create(project_id=case_study.project_id, repository_path=path)
    if invalid:
        raise RuntimeError('Güvenle normalize edilemeyen GitHub repository verileri: ' + ', '.join(invalid))
    for update in ProjectUpdate.objects.all().iterator():
        update.description = update.note or ''
        update.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_project_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='repository_path',
            field=models.CharField(default='', max_length=201),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(blank=True, upload_to=projects.models.project_media_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf', 'mp4', 'webm']), projects.models.validate_project_upload_size, projects.models.validate_project_upload_content]),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('recruitment_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('technologies', models.ManyToManyField(blank=True, related_name='teams', to='projects.technology')),
                ('work_areas', models.ManyToManyField(blank=True, related_name='teams', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.team', verbose_name='Ekip'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_records', to='projects.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='bst_teams', through='projects.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamOpenRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_technologies', models.ManyToManyField(blank=True, related_name='team_open_roles', to='projects.technology')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_roles', to='projects.team')),
            ],
            options={
                'ordering': ['-is_open', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_like')],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_role', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('accepted', 'Kabul edildi'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'invited_user'), name='unique_pending_team_invite')],
            },
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_membership'),
        ),
        migrations.RunPython(preserve_repository_and_updates, migrations.RunPython.noop),
        migrations.RemoveField(model_name='projectcasestudy', name='github_url'),
        migrations.RemoveField(model_name='projectrepository', name='contributor_count'),
        migrations.RemoveField(model_name='projectrepository', name='contributors'),
        migrations.RemoveField(model_name='projectrepository', name='description'),
        migrations.RemoveField(model_name='projectrepository', name='forks'),
        migrations.RemoveField(model_name='projectrepository', name='github_updated_at'),
        migrations.RemoveField(model_name='projectrepository', name='languages'),
        migrations.RemoveField(model_name='projectrepository', name='last_sync_attempt_at'),
        migrations.RemoveField(model_name='projectrepository', name='name'),
        migrations.RemoveField(model_name='projectrepository', name='open_issue_count'),
        migrations.RemoveField(model_name='projectrepository', name='owner'),
        migrations.RemoveField(model_name='projectrepository', name='readme_url'),
        migrations.RemoveField(model_name='projectrepository', name='release_count'),
        migrations.RemoveField(model_name='projectrepository', name='releases'),
        migrations.RemoveField(model_name='projectrepository', name='repository_url'),
        migrations.RemoveField(model_name='projectrepository', name='stars'),
        migrations.RemoveField(model_name='projectrepository', name='sync_error'),
        migrations.RemoveField(model_name='projectrepository', name='sync_status'),
        migrations.RemoveField(model_name='projectrepository', name='synced_at'),
        migrations.RemoveField(model_name='projectupdate', name='note'),
    ]
