# Generated by Django 5.2.1 on 2026-08-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_projectcasestudy_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.projectcomment', verbose_name='Yanıtlanan yorum'),
        ),
    ]
