# Generated by Django 5.2.1 on 2026-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Herkese Açık'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Proje Görseli'), ('cover_image', 'Kapak Görseli'), ('project_logo', 'Proje Logosu'), ('video', 'Video'), ('demo', 'Demo'), ('document', 'Doküman'), ('pitch_deck', 'Yatırımcı Sunumu'), ('documentation', 'Proje Dokümantasyonu')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='projectmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('media_type__in', ['cover_image', 'project_logo', 'pitch_deck', 'documentation'])), fields=('project', 'media_type'), name='one_project_asset_per_type'),
        ),
    ]
