# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


TEAM_ROLE_CHOICES = [
    ('team_lead', 'Ekip Lideri'),
    ('tech_lead', 'Teknik Lider'),
    ('product_manager', 'Ürün Yöneticisi'),
    ('project_manager', 'Proje Yöneticisi'),
    ('business_analyst', 'İş / Sistem Analisti'),
    ('ui_ux', 'UI/UX Tasarımcısı'),
    ('frontend', 'Frontend Geliştirici'),
    ('backend', 'Backend Geliştirici'),
    ('fullstack', 'Full-stack Geliştirici'),
    ('mobile', 'Mobil Uygulama Geliştiricisi'),
    ('ai_ml', 'Yapay Zekâ / Makine Öğrenmesi'),
    ('data_science', 'Veri Bilimci / Analisti'),
    ('data_engineering', 'Veri Mühendisi'),
    ('database', 'Veritabanı Uzmanı'),
    ('devops_cloud', 'DevOps / Bulut Uzmanı'),
    ('cybersecurity', 'Siber Güvenlik Uzmanı'),
    ('qa_test', 'Test / Kalite Güvence'),
    ('embedded_iot', 'Gömülü Sistemler / IoT'),
    ('game', 'Oyun Geliştiricisi'),
    ('blockchain', 'Blockchain / Web3 Geliştiricisi'),
    ('research', 'Araştırma / Akademik Destek'),
    ('documentation', 'Teknik Dokümantasyon'),
    ('general', 'Genel Ekip Üyesi'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectmedia_is_public_alter_projectmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='proposed_role',
            field=models.CharField(choices=TEAM_ROLE_CHOICES, default='general', max_length=120),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=TEAM_ROLE_CHOICES, default='general', max_length=120),
        ),
        migrations.AlterField(
            model_name='teamopenrole',
            name='title',
            field=models.CharField(choices=TEAM_ROLE_CHOICES, max_length=120),
        ),
    ]
