# Generated by Django 5.2.17 on 2026-09-22 18:36

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import unicodedata
import projects.storage
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def migrate_legacy_courses(apps, schema_editor):
    db = schema_editor.connection.alias
    Course = apps.get_model('projects', 'Course')
    ProjectRequest = apps.get_model('projects', 'ProjectRequest')
    Project = apps.get_model('projects', 'Project')
    normalized = {}
    for announcement in ProjectRequest.objects.using(db).order_by('pk').iterator():
        raw_name = announcement.course or ''
        name = raw_name.strip()
        if not name:
            if raw_name:
                announcement.legacy_course_unmapped = raw_name
                announcement.save(using=db, update_fields=['legacy_course_unmapped'])
            continue
        key = unicodedata.normalize('NFKC', name).casefold()
        if key not in normalized:
            base = slugify(name) or 'ders'
            slug = base
            index = 2
            while Course.objects.using(db).filter(slug=slug).exists():
                slug = f'{base[:210]}-{index}'
                index += 1
            normalized[key] = Course.objects.using(db).create(name=name, slug=slug)
        announcement.legacy_course_unmapped = raw_name
        if not announcement.project_type.requires_course:
            announcement.save(using=db, update_fields=['legacy_course_unmapped'])
            continue
        announcement.legacy_course_ref_id = normalized[key].pk
        announcement.save(using=db, update_fields=['legacy_course_unmapped', 'legacy_course_ref'])
        if announcement.created_project_id:
            Project.objects.using(db).filter(pk=announcement.created_project_id, project_request__isnull=True,
                                             project_type__requires_course=True, course__isnull=True).update(course_id=normalized[key].pk)
        Project.objects.using(db).filter(project_request_id=announcement.pk,
                                         project_type__requires_course=True, course__isnull=True).update(course_id=normalized[key].pk)


def restore_legacy_courses(apps, schema_editor):
    db = schema_editor.connection.alias
    ProjectRequest = apps.get_model('projects', 'ProjectRequest')
    for announcement in ProjectRequest.objects.using(db).select_related('legacy_course_ref').order_by('pk').iterator():
        announcement.course = announcement.legacy_course_unmapped or (
            announcement.legacy_course_ref.name if announcement.legacy_course_ref_id else None
        )
        announcement.save(using=db, update_fields=['course'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_team_role_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), condition=models.Q(('code', ''), _negated=True), name='course_code_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.course'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='legacy_course_unmapped',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='legacy_course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='projects.course'),
        ),
        migrations.RunPython(migrate_legacy_courses, restore_legacy_courses),
        migrations.RemoveField(model_name='projectrequest', name='course'),
        migrations.RenameField(model_name='projectrequest', old_name='legacy_course_ref', new_name='course'),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('completion_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_late', models.BooleanField(default=False, editable=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='projects.projectmilestone')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestoneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('APPROVED', 'Onaylandı'), ('REVISION_REQUIRED', 'Revizyon gerekli')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='projects.projectmilestonesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=projects.storage.project_milestone_private_storage, upload_to=projects.storage.milestone_file_path)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='projects.projectmilestonesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneSubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='projects.projectmilestonesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='projects.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'instructor'), name='unique_course_instructor')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_project_milestone_order'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='positive_project_milestone_score'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestonesubmission',
            constraint=models.UniqueConstraint(fields=('milestone', 'attempt_number'), name='unique_milestone_attempt'),
        ),
    ]
