# Generated by Django 5.2.17 on 2026-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_course_project_course_alter_projectrequest_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
