# Generated by Django 5.2.17 on 2026-09-23 19:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify
import unicodedata


FALL = (
    ('BST 103', 'Algoritma Bilgisayar Programlamaya Giriş', 1, 'Harun ÖZKİŞİ'),
    ('BST 105', 'Bilgisayara Giriş', 1, 'Gürkan KOLAYLI'),
    ('BST 201', 'Veri Yapıları', 2, 'Egemen TEKKANAT'),
    ('BST 203', 'Sayısal Devre Tasarımı', 2, 'Onur KARA'),
    ('BST 207', 'Python Programlama', 2, 'Murat TOPALOĞLU'),
    ('BST 209', 'Nesne Tabanlı Programlama', 2, 'Murat TOPALOĞLU'),
    ('BST 211', 'Sanallaştırma ve Bulut Hesaplama', 2, 'Onur KARA'),
    ('BST 301', 'Görsel Programlama I', 3, 'Egemen TEKKANAT'),
    ('BST 303', 'Yazılım Mühendisliği', 3, 'Onur KARA'),
    ('BST 305', 'İşletim Sistemleri', 3, 'Egemen TEKKANAT'),
    ('BST 307', 'İnternet Programlama', 3, 'Onur KARA'),
    ('BST 401', 'Bitirme Projesi I', 4, 'Murat TOPALOĞLU', 'Onur KARA', 'Egemen TEKKANAT', 'Harun ÖZKİŞİ'),
    ('BST 403', 'Veritabanı Yönetim Sistemleri', 4, 'Egemen TEKKANAT'),
    ('BST 405', 'Bilgisayar Ağ Yönetimi', 4, 'Onur KARA'),
)

SPRING = (
    ('BST 104', 'Bilgisayar Programlama', 1),
    ('BST 202', 'Programlama Dilleri Uygulamaları', 2),
    ('BST 204', 'Bilişimde Veri Güvenliği', 2),
    ('BST 206', 'Bilgisayar Mimarisi', 2),
    ('BST 208', 'Linux Sistemleri Yönetimi', 2),
    ('BST 210', 'Kriptografi', 2),
    ('BST 212', 'Proje Yönetimi', 2),
    ('BST 302', 'Görsel Programlama II', 3),
    ('BST 304', 'Veritabanı Yönetim Sistemleri', 3),
    ('BST 306', 'Bilgisayar Ağlarına Giriş', 3),
    ('BST 308', 'Mikroişlemciler', 3),
    ('BST 402', 'Bitirme Projesi II', 4),
    ('BST 404', 'Sistem Programlama', 4),
)


def _name(value):
    return ' '.join(unicodedata.normalize('NFKC', value or '').split()).casefold()


def seed_2026_2027(apps, schema_editor):
    Course = apps.get_model('projects', 'Course')
    Entry = apps.get_model('projects', 'CourseCatalogEntry')
    Assignment = apps.get_model('projects', 'CourseInstructor')
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    alias = schema_editor.connection.alias
    courses = list(Course.objects.using(alias).all())
    teachers = []
    teacher_ids = set(Profile.objects.using(alias).filter(user_type='teacher').values_list('user_id', flat=True))
    for user in User.objects.using(alias).filter(is_active=True, pk__in=teacher_ids):
        teachers.append((_name(f'{user.first_name} {user.last_name}'), user))

    for semester, rows in (('FALL', FALL), ('SPRING', SPRING)):
        for code, name, level, *names in rows:
            canonical = code.replace(' ', '').casefold()
            matches = [item for item in courses if item.code.replace(' ', '').casefold() == canonical]
            if len(matches) > 1:
                raise ValueError(f'{code} için birden fazla mevcut ders kaydı var; elle çözülmeli.')
            if matches:
                course = matches[0]
                if course.code != code or not course.is_active:
                    course.code = code
                    course.is_active = True
                    course.save(using=alias, update_fields=['code', 'is_active'])
            else:
                base = slugify(code)
                slug = base
                suffix = 2
                while Course.objects.using(alias).filter(slug=slug).exists():
                    slug = f'{base}-{suffix}'
                    suffix += 1
                course = Course.objects.using(alias).create(code=code, name=name, slug=slug)
                courses.append(course)
            Entry.objects.using(alias).update_or_create(
                course_id=course.pk, academic_year='2026-2027', semester=semester,
                defaults={'class_level': level, 'display_name': name, 'is_active': True},
            )
            for expected in names:
                matched = [user for full_name, user in teachers if full_name == _name(expected)]
                if len(matched) != 1:
                    continue
                Assignment.objects.using(alias).update_or_create(
                    course_id=course.pk, instructor_id=matched[0].pk,
                    defaults={'is_active': True},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_projectmilestone_max_score'),
        ('accounts', '0021_alter_portfoliocertificate_credential_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('FALL', 'Güz'), ('SPRING', 'Bahar')], max_length=6)),
                ('class_level', models.PositiveSmallIntegerField()),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_entries', to='projects.course')),
            ],
            options={
                'ordering': ['semester', 'class_level', 'course__code'],
                'constraints': [models.UniqueConstraint(fields=('course', 'academic_year', 'semester'), name='course_catalog_year_sem_unique'), models.CheckConstraint(condition=models.Q(('class_level__gte', 1), ('class_level__lte', 4)), name='course_catalog_class_1_4')],
            },
        ),
        migrations.RunPython(seed_2026_2027, migrations.RunPython.noop),
    ]
