# Generated by Django 5.2.17 on 2026-09-25 01:37

import django.db.models.deletion
import projects.course_work_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_course_catalog_2026_2027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignmentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('due_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='assignment_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_progress', to='projects.courseassignmentcheckpoint'),
        ),
        migrations.CreateModel(
            name='CourseProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('GROUP', 'Grup')], default='INDIVIDUAL', max_length=10)),
                ('min_team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('join_deadline', models.DateTimeField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('repository_required', models.BooleanField(default=False)),
                ('invitation_token', models.CharField(default=projects.course_work_models.invitation_token, editable=False, max_length=64, unique=True)),
                ('invitation_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='projects.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseassignmentcheckpoint',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='projects.courseprojectassignment'),
        ),
        migrations.CreateModel(
            name='CourseProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='projects.courseprojectassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='projects.courseprojectassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_project_participations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='projects.courseprojectteam')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='projects.courseprojectassignment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_project_work', to='projects.project')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work', to='projects.courseprojectteam')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignmentExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_items', to='projects.courseassignmentcheckpoint')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('checkpoint', 'order'), name='unique_course_assignment_expectation_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseassignmentcheckpoint',
            constraint=models.UniqueConstraint(fields=('assignment', 'order'), name='unique_course_assignment_checkpoint_order'),
        ),
        migrations.AddConstraint(
            model_name='courseprojectteam',
            constraint=models.UniqueConstraint(fields=('assignment', 'name'), name='unique_course_project_team_name'),
        ),
        migrations.AddConstraint(
            model_name='courseprojectparticipation',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_course_project_participation'),
        ),
        migrations.AddConstraint(
            model_name='courseprojectwork',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('team__isnull', True)), models.Q(('owner__isnull', True), ('team__isnull', False)), _connector='OR'), name='course_work_owner_xor_team'),
        ),
        migrations.AddConstraint(
            model_name='courseprojectwork',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('assignment', 'owner'), name='unique_individual_course_work'),
        ),
    ]
