# Generated by Django 5.2.17 on 2026-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_courseassignmentcheckpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
