# Generated by Django 5.2.17 on 2026-09-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_projectmilestone_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprojectassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='courseprojectassignment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='courseprojectassignment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseprojectassignment',
            name='lifecycle_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
