# Generated by Django 5.2.17 on 2026-09-30 19:23

import django.db.models.deletion
import projects.course_requirements
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_creation_tokens(apps, schema_editor):
    Assignment = apps.get_model('projects', 'CourseProjectAssignment')
    alias = schema_editor.connection.alias
    for pk in Assignment.objects.using(alias).filter(creation_token__isnull=True).values_list('pk', flat=True).iterator():
        Assignment.objects.using(alias).filter(pk=pk, creation_token__isnull=True).update(creation_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_restore_full_bst_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrivateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CourseProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('GROUP', 'Grup')], default='INDIVIDUAL', max_length=10)),
                ('min_team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repository_required', models.BooleanField(default=False)),
                ('plan', models.JSONField(default=list, blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneSubmissionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='courseassignmentcheckpoint',
            name='evidence_requirements',
            field=models.JSONField(default=projects.course_requirements.default_requirements, validators=[projects.course_requirements.validate_requirements]),
        ),
        migrations.AddField(
            model_name='courseassignmentcheckpoint',
            name='max_points',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='courseassignmentcheckpoint',
            name='scoring_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprojectassignment',
            name='creation_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_creation_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courseprojectassignment', name='creation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='projectmilestonesubmission',
            name='requirement_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddConstraint(
            model_name='courseprojectassignment',
            constraint=models.UniqueConstraint(fields=('instructor', 'creation_token'), name='course_assignment_creation_unique'),
        ),
        migrations.AddField(
            model_name='courseprivateevaluation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseprivateevaluation',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_evaluations', to='projects.projectmilestonereview'),
        ),
        migrations.AddField(
            model_name='courseprojecttemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_project_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestonesubmissionreference',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='projects.projectmilestonesubmission'),
        ),
        migrations.AddConstraint(
            model_name='courseprivateevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', models.F('max_points'))), _connector='OR'), name='course_private_score_bounds'),
        ),
    ]
