# Generated by Django 5.2.1 on 2026-03-10 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Article URL')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image')),
                ('article_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Article Type')),
                ('article_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Article Category')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='Show on Homepage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date'],
            },
        ),
    ]
