# Generated by Django 5.2.1 on 2025-05-17 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Kaynak URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-date'],
            },
        ),
    ]
