# Generated by Django 5.2.1 on 2025-05-27 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Haber Linki')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Görsel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
        ),
    ]
