# Generated by Django 5.2.1 on 2026-04-15 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Teknoloji'), ('university', 'Üniversite'), ('software', 'Yazılım'), ('sector', 'Sektörel')], max_length=50, null=True, verbose_name='AI Kategori'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Kaynak URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Haber Türü'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Göster'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Haber URL'),
        ),
    ]
