# Generated by Django 5.2.1 on 2025-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_category_news_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='Anasayfa'),
        ),
    ]
