# Generated by Django 5.2.1 on 2026-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Görsel URL'),
        ),
    ]
