# Generated by Django 5.2.1 on 2026-08-13 16:38

from django.db import migrations, models
from django.utils.text import slugify


def populate_article_slugs(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    used = set(Article.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))
    for article in Article.objects.filter(models.Q(slug__isnull=True) | models.Q(slug='')).order_by('pk').iterator():
        base = slugify(article.title) or f'haber-{article.pk}'
        candidate = base
        counter = 2
        while candidate in used:
            candidate = f'{base}-{counter}'
            counter += 1
        article.slug = candidate
        article.save(update_fields=['slug'])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newskeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, null=True),
        ),
        migrations.RunPython(populate_article_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, unique=True),
        ),
    ]
