# Generated by Django 5.2.1 on 2026-01-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
