# Generated by Django 5.2.1 on 2026-08-20 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analyticsevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_comment', 'Proje yorumu'), ('project_update', 'Proje güncellemesi'), ('project_approved', 'Proje onayı'), ('application_accepted', 'Başvuru kabulü'), ('application_rejected', 'Başvuru reddi'), ('mentorship_request', 'Mentorluk talebi'), ('opportunity', 'Kariyer ilanı'), ('event', 'Etkinlik'), ('system', 'Sistem'), ('team_invite', 'Ekip daveti'), ('team_invite_result', 'Ekip daveti sonucu'), ('project_like_milestone', 'Proje beğeni eşiği'), ('project_featured', 'Proje öne çıkarıldı'), ('website_review', 'Kişisel web sitesi incelemesi'), ('alumni_registration', 'Mezun kayıt talebi'), ('moderation', 'Moderasyon'), ('pending_task', 'Bekleyen yönetim görevi')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe_key'),
        ),
    ]
