# Generated by Django 5.2.1 on 2026-08-27 14:42

import core.link_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_dedupe_key_notification_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('navigation', 'Navigasyon'), ('resources', 'Kaynaklar'), ('contact', 'İletişim'), ('legal', 'Yasal bağlantılar'), ('contributors', 'Katkıda Bulunanlar')], max_length=20, verbose_name='Bölüm')),
                ('label', models.CharField(max_length=100, verbose_name='Görünen ad')),
                ('url', models.CharField(max_length=500, validators=[core.link_validation.validate_footer_url], verbose_name='Bağlantı')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Yeni sekmede aç')),
            ],
            options={
                'verbose_name': 'Footer bağlantısı',
                'verbose_name_plural': 'Footer bağlantıları',
                'ordering': ['section', 'sort_order', 'pk'],
            },
        ),
    ]
