# Generated by Django 5.2.17 on 2026-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_footer_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_comment', 'Proje yorumu'), ('project_update', 'Proje güncellemesi'), ('project_approved', 'Proje onayı'), ('application_accepted', 'Başvuru kabulü'), ('application_rejected', 'Başvuru reddi'), ('mentorship_request', 'Mentorluk talebi'), ('opportunity', 'Kariyer ilanı'), ('event', 'Etkinlik'), ('system', 'Sistem'), ('team_invite', 'Ekip daveti'), ('team_invite_result', 'Ekip daveti sonucu'), ('project_like_milestone', 'Proje beğeni eşiği'), ('project_milestone', 'Proje aşaması'), ('project_featured', 'Proje öne çıkarıldı'), ('website_review', 'Kişisel web sitesi incelemesi'), ('alumni_registration', 'Mezun kayıt talebi'), ('moderation', 'Moderasyon'), ('pending_task', 'Bekleyen yönetim görevi')], db_index=True, max_length=32),
        ),
    ]
