# Generated by Django 5.2.1 on 2025-05-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', verbose_name='Ekler'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('research', 'Araştırma'), ('development', 'Geliştirme'), ('design', 'Tasarım'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Herkese Açık'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='Takım Üyeleri'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Proje Açıklaması'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Proje URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planlama'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('on_hold', 'Beklemede')], default='planning', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='Danışman'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Proje Başlığı'),
        ),
    ]
