# Generated by Django 5.2.1 on 2025-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_level',
            field=models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('Alt', 'Altdan Devam Ediyor')], default='1', max_length=10),
        ),
    ]
