# Generated by Django 5.2.1 on 2026-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0005_alter_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='projects.technology'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_level',
            field=models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('alt', 'Altdan Devam Ediyor'), ('bitir', 'Bitirdi')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='Bilişim Sistemleri ve Teknolojileri', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Öğretim Üyesi'), ('alumni', 'Mezun'), ('staff_student', 'Görevli Öğrenci')], default='student', max_length=15),
        ),
    ]
