# Generated by Django 5.2.1 on 2025-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='Bilişim Sistemleri ve Teknolojileri', max_length=100, null=True),
        ),
    ]
