# Generated by Django 5.2.1 on 2026-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher_title',
            field=models.CharField(blank=True, choices=[('', 'Ünvan Seçin'), ('prof_dr', 'Prof. Dr.'), ('doc_dr', 'Doç. Dr.'), ('dr', 'Dr.'), ('arastirma_gorevlisi', 'Araştırma Görevlisi'), ('ogretim_gorevlisi', 'Öğretim Görevlisi'), ('okutman', 'Okutman'), ('uzman', 'Uzman')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Akademisyen'), ('alumni', 'Mezun'), ('staff_student', 'Görevli Öğrenci')], default='student', max_length=15),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
