# Generated by Django 5.2.1 on 2025-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='graduation_year',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_level',
            field=models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('alt', 'Altdan Devam Ediyor'), ('bitir', 'Bitirdi')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Öğretim Üyesi'), ('alumni', 'Mezun'), ('staff_student', 'Görevli Öğrenci')], default='student', max_length=15),
        ),
    ]
