# Generated by Django 5.2.1 on 2025-10-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_user_name_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='surname',
        ),
    ]
