# Generated by Django 5.2.1 on 2026-08-13 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fill_public_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_announcements', models.BooleanField(default=False)),
                ('email_project_updates', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms', 'Kullanım Koşulları'), ('privacy_notice', 'KVKK Aydınlatma Metni'), ('marketing_email', 'Tanıtım ve Duyuru E-postaları')], max_length=30)),
                ('text_version', models.CharField(max_length=30)),
                ('accepted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-created_at'], name='consent_user_type_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', 'Verilerimi Dışa Aktar'), ('anonymize', 'Hesabımı Anonimleştir'), ('delete', 'Hesabımı Sil')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('reviewing', 'İnceleniyor'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='pending', max_length=12)),
                ('explanation', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_subject_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'reviewing'])), fields=('user', 'request_type'), name='one_open_data_request_per_type')],
            },
        ),
    ]
