# Generated by Django 5.2.1 on 2025-10-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_last_name_userprofile_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
