# Generated by Django 5.2.1 on 2026-08-13 16:44

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def hash_pending_codes(apps, schema_editor):
    EmailVerification = apps.get_model('accounts', 'EmailVerification')
    for verification in EmailVerification.objects.exclude(code='').iterator():
        verification.code_hash = make_password(verification.code)
        verification.code = ''
        verification.save(update_fields=['code', 'code_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_communicationpreference_consentrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(hash_pending_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
