# Generated by Django 5.2.1 on 2026-08-13 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_communicationpreference_email_application_results_and_more'),
        ('projects', '0020_alter_projectcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('student_number__isnull', False), models.Q(('student_number', ''), _negated=True)), fields=('student_number',), name='unique_nonempty_student_number'),
        ),
    ]
