# Generated by Django 5.2.1 on 2026-08-20 16:45

import accounts.validators
import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.conf import settings
from django.db import migrations, models
from urllib.parse import unquote, urlparse
import re


GITHUB_RE = re.compile(r'^(?!-)(?!.*--)[A-Za-z0-9-]{1,39}(?<!-)$')
LINKEDIN_RE = re.compile(r'^[A-Za-z0-9](?:[A-Za-z0-9-]{1,98}[A-Za-z0-9])?$')


def _github_username(value):
    value = (value or '').strip()
    if not value:
        return ''
    parsed = urlparse(value)
    if parsed.scheme:
        if parsed.scheme != 'https' or parsed.hostname not in {'github.com', 'www.github.com'}:
            return None
        parts = [part for part in parsed.path.strip('/').split('/') if part]
        value = parts[0] if len(parts) == 1 else ''
    return value if GITHUB_RE.fullmatch(value) else None


def _linkedin_slug(value):
    value = (value or '').strip()
    if not value:
        return ''
    parsed = urlparse(value)
    if parsed.scheme:
        if parsed.scheme != 'https' or parsed.hostname not in {'linkedin.com', 'www.linkedin.com'}:
            return None
        parts = [unquote(part) for part in parsed.path.strip('/').split('/') if part]
        value = parts[1] if len(parts) == 2 and parts[0].casefold() == 'in' else ''
    return value if LINKEDIN_RE.fullmatch(value) else None


def preserve_and_normalize_profile_data(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    PasswordReset = apps.get_model('accounts', 'PasswordReset')
    UserModerationAction = apps.get_model('accounts', 'UserModerationAction')
    WebsiteModerationHistory = apps.get_model('accounts', 'WebsiteModerationHistory')
    invalid = []
    for profile in Profile.objects.all().iterator():
        github = _github_username(profile.github_url)
        linkedin = _linkedin_slug(profile.linkedin_url)
        if github is None:
            invalid.append(f'Profile#{profile.pk}:github')
        if linkedin is None:
            invalid.append(f'Profile#{profile.pk}:linkedin')
        if invalid:
            continue
        if profile.user_type not in {'student', 'staff_student'}:
            profile.class_level = None
        elif profile.class_level not in {'1', '2', '3', '4'}:
            invalid.append(f'Profile#{profile.pk}:class_level')
            continue
        profile.github_username = github
        profile.linkedin_slug = linkedin
        if profile.personal_website:
            profile.website_url = profile.personal_website
            profile.website_status = 'pending'
        profile.save(update_fields=['github_username', 'linkedin_slug', 'website_url', 'website_status', 'class_level'])
        if profile.website_url:
            WebsiteModerationHistory.objects.create(
                profile_id=profile.pk,
                website_url=profile.website_url,
                status='pending',
                description='Eski kişisel web sitesi incelemeye taşındı.',
            )
    if invalid:
        raise RuntimeError('Güvenle normalize edilemeyen profil verileri: ' + ', '.join(invalid))
    for reset in PasswordReset.objects.exclude(code='').iterator():
        reset.code_hash = make_password(reset.code)
        reset.code = ''
        reset.save(update_fields=['code', 'code_hash'])
    for action in UserModerationAction.objects.all().iterator():
        action.description = action.reason
        action.reason = 'other'
        action.save(update_fields=['reason', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_showcase_projects'),
        ('projects', '0021_remove_projectcasestudy_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(validators=[accounts.validators.validate_public_website])),
                ('status', models.CharField(choices=[('pending', 'İnceleme bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], max_length=12)),
                ('reason', models.CharField(blank=True, choices=[('inappropriate_content', 'Uygunsuz içerik'), ('spam', 'Spam'), ('harassment', 'Taciz / kötü davranış'), ('misleading', 'Sahte / yanıltıcı bilgi'), ('community_violation', 'Topluluk kuralları ihlali'), ('security_concern', 'Güvenlik şüphesi'), ('inappropriate_profile', 'Uygunsuz profil içeriği'), ('other', 'Diğer')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('moderate_accounts', 'Can perform limited account moderation'), ('end_user_sessions', 'Can terminate active user sessions'), ('review_profile_websites', 'Can review personal website submissions'), ('review_user_reports', 'Can review user reports'), ('review_alumni_registrations', 'Can review alumni registration requests'), ('review_project_requests', 'Can review project requests'), ('review_collaborations', 'Can perform first review of collaboration requests')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=39, validators=[accounts.validators.validate_github_username]),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_slug',
            field=models.CharField(blank=True, max_length=100, validators=[accounts.validators.validate_linkedin_slug]),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_moderation_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_rejection_reason',
            field=models.CharField(blank=True, choices=[('inappropriate_content', 'Uygunsuz içerik'), ('spam', 'Spam'), ('harassment', 'Taciz / kötü davranış'), ('misleading', 'Sahte / yanıltıcı bilgi'), ('community_violation', 'Topluluk kuralları ihlali'), ('security_concern', 'Güvenlik şüphesi'), ('inappropriate_profile', 'Uygunsuz profil içeriği'), ('other', 'Diğer')], max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_websites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_status',
            field=models.CharField(blank=True, choices=[('pending', 'İnceleme bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, validators=[accounts.validators.validate_public_website]),
        ),
        migrations.AddField(
            model_name='usermoderationaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_level',
            field=models.CharField(blank=True, choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Akademisyen'), ('alumni', 'Mezun'), ('staff_student', 'BST Yetkilisi')], default='student', max_length=15),
        ),
        migrations.AlterField(
            model_name='usermoderationaction',
            name='reason',
            field=models.CharField(choices=[('inappropriate_content', 'Uygunsuz içerik'), ('spam', 'Spam'), ('harassment', 'Taciz / kötü davranış'), ('misleading', 'Sahte / yanıltıcı bilgi'), ('community_violation', 'Topluluk kuralları ihlali'), ('security_concern', 'Güvenlik şüphesi'), ('inappropriate_profile', 'Uygunsuz profil içeriği'), ('other', 'Diğer')], max_length=32),
        ),
        migrations.AddField(
            model_name='websitemoderationhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_website_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websitemoderationhistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='website_moderation_history', to='accounts.profile'),
        ),
        migrations.RunPython(preserve_and_normalize_profile_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_level__in', ['1', '2', '3', '4']), ('user_type__in', ['student', 'staff_student'])), models.Q(('user_type__in', ['teacher', 'alumni']), ('class_level__isnull', True)), _connector='OR'), name='class_level_matches_student_role'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_website',
        ),
    ]
