# Generated by Django 5.2.1 on 2026-08-20 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_websitemoderationhistory_alter_profile_options_and_more'),
        ('projects', '0021_remove_projectcasestudy_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='class_level_matches_student_role',
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_level__in', ['1', '2', '3', '4']), ('class_level__isnull', False), ('user_type__in', ['student', 'staff_student'])), models.Q(('user_type__in', ['teacher', 'alumni']), ('class_level__isnull', True)), _connector='OR'), name='class_level_matches_student_role'),
        ),
    ]
