# Generated by Django 5.2.1 on 2026-08-29 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_enforce_nonnull_student_class'),
        ('projects', '0023_projectmedia_is_public_alter_projectmedia_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=1000, verbose_name='Kısa Tanıtım')),
                ('motivation', models.TextField(max_length=1500, verbose_name='Kayıt Olma Nedeni')),
                ('wants_to_share', models.BooleanField(default=False, verbose_name='İçerik Paylaşmak İstiyor')),
                ('content_plan', models.TextField(blank=True, max_length=2000, verbose_name='Planlanan İçerik Türleri')),
                ('status', models.CharField(choices=[('visitor', 'Ziyaretçi olarak kayıtlı'), ('pending', 'Katkıcı incelemesi bekleniyor'), ('approved', 'Katkıcı olarak onaylandı'), ('rejected', 'Katkıcı başvurusu reddedildi')], db_index=True, default='visitor', max_length=12)),
                ('reviewer_note', models.TextField(blank=True, max_length=1000, verbose_name='İnceleme Notu')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Topluluk kaydı',
                'verbose_name_plural': 'Topluluk kayıtları',
                'ordering': ['-created_at'],
                'permissions': [('review_contributor_applications', 'Can review contributor applications')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='class_level_matches_student_role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Akademisyen'), ('alumni', 'Mezun'), ('staff_student', 'BST Yetkilisi'), ('visitor', 'Ziyaretçi'), ('contributor', 'Katkıcı')], default='student', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_level__in', ['1', '2', '3', '4']), ('class_level__isnull', False), ('user_type__in', ['student', 'staff_student'])), models.Q(('user_type__in', ['teacher', 'alumni', 'visitor', 'contributor']), ('class_level__isnull', True)), _connector='OR'), name='class_level_matches_student_role'),
        ),
        migrations.AddField(
            model_name='communityregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributor_applications', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen'),
        ),
        migrations.AddField(
            model_name='communityregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_registration', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
