# Generated by Django 5.2.1 on 2026-08-29 22:36

from django.conf import settings
from django.db import migrations, models


def rename_contributor_role(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(user_type='contributor').update(user_type='approved_member')


def restore_contributor_role(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(user_type='approved_member').update(user_type='contributor')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_communityregistration_and_more'),
        ('projects', '0023_projectmedia_is_public_alter_projectmedia_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityregistration',
            options={'ordering': ['-created_at'], 'permissions': [('review_contributor_applications', 'Can review approved member applications')], 'verbose_name': 'Onaylı Üye başvurusu', 'verbose_name_plural': 'Onaylı Üye başvuruları'},
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='class_level_matches_student_role',
        ),
        migrations.RunPython(rename_contributor_role, restore_contributor_role),
        migrations.AddField(
            model_name='communityregistration',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Ek Açıklama'),
        ),
        migrations.AddField(
            model_name='communityregistration',
            name='reference_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='GitHub / LinkedIn / Portfolyo Bağlantısı'),
        ),
        migrations.AlterField(
            model_name='communityregistration',
            name='content_plan',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Planlanan Paylaşım Türleri'),
        ),
        migrations.AlterField(
            model_name='communityregistration',
            name='motivation',
            field=models.TextField(max_length=1500, verbose_name='Onaylı Üye Olma Nedeni'),
        ),
        migrations.AlterField(
            model_name='communityregistration',
            name='status',
            field=models.CharField(choices=[('visitor', 'Ziyaretçi olarak kayıtlı'), ('pending', 'Onaylı Üye incelemesi bekleniyor'), ('approved', 'Onaylı Üye olarak onaylandı'), ('rejected', 'Onaylı Üye başvurusu reddedildi')], db_index=True, default='visitor', max_length=12),
        ),
        migrations.AlterField(
            model_name='communityregistration',
            name='wants_to_share',
            field=models.BooleanField(default=False, verbose_name='Onaylı Üye Başvurusu Yapıldı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Akademisyen'), ('alumni', 'Mezun'), ('staff_student', 'BST Yetkilisi'), ('visitor', 'Ziyaretçi'), ('approved_member', 'Onaylı Üye')], default='student', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_level__in', ['1', '2', '3', '4']), ('class_level__isnull', False), ('user_type__in', ['student', 'staff_student'])), models.Q(('user_type__in', ['teacher', 'alumni', 'visitor', 'approved_member']), ('class_level__isnull', True)), _connector='OR'), name='class_level_matches_student_role'),
        ),
    ]
