# Generated by Django 5.2.1 on 2026-08-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_communityregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='İlk girişte şifre değişikliği gerekli'),
        ),
    ]
