# Generated by Django 5.2.17 on 2026-09-25 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_portfoliocertificate_credential_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocertificate',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliocertificate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocertificate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfoliocertificate',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=8),
        ),
    ]
