# Generated by Django 5.2.17 on 2026-09-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_alter_team_role_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('FALL', 'Güz'), ('SPRING', 'Bahar')], max_length=6)),
                ('starts_at', models.DateTimeField()),
                ('midterm_at', models.DateTimeField()),
                ('final_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', 'semester'],
                'indexes': [models.Index(fields=['is_active', 'starts_at'], name='cap_term_active_start_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'semester'), name='unique_capstone_academic_term'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_capstone_term'), models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('midterm_at')), ('midterm_at__lt', models.F('final_at'))), name='capstone_term_dates_chronological')],
            },
        ),
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capstone', to='projects.project')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_projects', to='capstone.capstoneterm')),
            ],
            options={
                'ordering': ['term', 'project_id'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FIRST_REVIEW', 'İlk Değerlendirme'), ('MIDTERM_REVIEW', 'Ara Değerlendirme'), ('POST_MIDTERM_REVIEW', 'Ara Değerlendirme Sonrası'), ('FINAL_REVIEW', 'Final Değerlendirmesi')], max_length=22)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='capstone.capstoneproject')),
            ],
            options={
                'ordering': ['due_at', 'kind'],
                'indexes': [models.Index(fields=['capstone_project', 'due_at'], name='cap_checkpoint_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('capstone_project', 'kind'), name='unique_capstone_checkpoint_kind')],
            },
        ),
        migrations.AddIndex(
            model_name='capstoneproject',
            index=models.Index(fields=['term', 'created_at'], name='cap_project_term_date_idx'),
        ),
    ]
