# Generated by Django 5.2.17 on 2026-09-21 20:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_capstoneenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(max_length=5000)),
                ('required_file_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='capstone.capstoneproject')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='capstone.capstonecheckpoint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_capstone_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'created_at'],
                'indexes': [models.Index(fields=['checkpoint', 'due_at'], name='cap_task_checkpoint_due_idx'), models.Index(fields=['capstone_project', 'due_at'], name='cap_task_project_due_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('required_file_count__gte', 1), ('required_file_count__lte', 20)), name='cap_task_file_count_range')],
            },
        ),
    ]
