# Generated by Django 5.2.17 on 2026-09-21 21:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_capstonetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_at', models.DateTimeField(editable=False)),
                ('is_late', models.BooleanField(default=False, editable=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_submission_attempts', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attempts', to='capstone.capstonetask')),
            ],
            options={
                'ordering': ['task_id', 'attempt_number'],
                'constraints': [models.UniqueConstraint(fields=('task', 'attempt_number'), name='unique_capstone_task_attempt'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='cap_submission_attempt_number_gte_1')],
            },
        ),
    ]
