# Generated by Django 5.2.17 on 2026-09-21 21:42

import capstone.models
import capstone.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_capstonesubmissionattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=capstone.storage.capstone_private_storage, upload_to=capstone.models.capstone_submission_file_upload_to)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='capstone.capstonesubmissionattempt')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
