# Generated by Django 5.2.17 on 2026-09-21 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_capstonesubmissionfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneSubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Kabul Edildi'), ('REVISION_REQUIRED', 'Revizyon Gerekli'), ('REJECTED', 'Reddedildi')], max_length=17)),
                ('feedback', models.TextField(max_length=5000)),
                ('reviewed_at', models.DateTimeField(editable=False)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_submission_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='capstone.capstonesubmissionattempt')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
