# Generated by Django 5.2.17 on 2026-09-22 20:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_capstonesubmissionreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneCheckpointEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(max_length=5000)),
                ('evaluated_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Danışman onayı bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('WITHDRAWN', 'Geri çekildi')], default='PENDING', max_length=10)),
                ('advisor_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='capstonecheckpoint',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='completed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_capstone_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='capstonecheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='cap_checkpoint_score_positive'),
        ),
        migrations.AddField(
            model_name='capstonecheckpointevaluation',
            name='checkpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='capstone.capstonecheckpoint'),
        ),
        migrations.AddField(
            model_name='capstonecheckpointevaluation',
            name='evaluated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_checkpoint_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capstoneproposal',
            name='requested_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_capstone_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capstoneproposal',
            name='resulting_capstone_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_proposal', to='capstone.capstoneproject'),
        ),
        migrations.AddField(
            model_name='capstoneproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_capstone_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capstoneproposal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capstoneproposal',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='capstone.capstoneterm'),
        ),
        migrations.AddIndex(
            model_name='capstoneproposal',
            index=models.Index(fields=['requested_advisor', 'status'], name='cap_proposal_advisor_idx'),
        ),
        migrations.AddConstraint(
            model_name='capstoneproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('term', 'student'), name='unique_pending_capstone_proposal'),
        ),
    ]
