# Generated by Django 5.2.17 on 2026-09-23 16:29

import capstone.academic_models
import capstone.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def backfill_existing_advisors(apps, schema_editor):
    Enrollment = apps.get_model('capstone', 'CapstoneEnrollment')
    CapstoneProject = apps.get_model('capstone', 'CapstoneProject')
    for enrollment in Enrollment.objects.filter(advisor__isnull=True).iterator():
        advisor_ids = list(CapstoneProject.objects.filter(
            term_id=enrollment.term_id, project__created_by_id=enrollment.student_id
        ).exclude(project__development_status='cancelled').exclude(
            project__advisor_id__isnull=True
        ).values_list('project__advisor_id', flat=True).distinct()[:2])
        if len(advisor_ids) == 1:
            Enrollment.objects.filter(pk=enrollment.pk, advisor__isnull=True).update(advisor_id=advisor_ids[0])


def guard_reverse_with_academic_data(apps, schema_editor):
    Enrollment = apps.get_model('capstone', 'CapstoneEnrollment')
    if Enrollment.objects.filter(advisor__isnull=False).exists():
        raise IrreversibleError('Danışman atamaları varken bu migration geri alınamaz.')
    for model in apps.get_app_config('capstone').get_models():
        if model.__name__.startswith('Capstone') and model.__name__ not in {
            'CapstoneTerm', 'CapstoneEnrollment', 'CapstoneProject', 'CapstoneCheckpoint',
            'CapstoneTask', 'CapstoneSubmissionAttempt', 'CapstoneSubmissionFile',
            'CapstoneSubmissionReview', 'CapstoneProposal', 'CapstoneCheckpointEvaluation',
        } and model.objects.exists():
            raise IrreversibleError('Yeni akademik süreç kayıtları varken bu migration geri alınamaz.')


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_capstonecheckpointevaluation_capstoneproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capstoneenrollment',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capstone_advisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capstoneenrollment',
            name='advisor_assigned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='capstoneenrollment',
            name='advisor_assigned_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capstone_advisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CapstoneAcademicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(editable=False)),
                ('is_late', models.BooleanField(default=False, editable=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attempt_number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneAcademicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Onaylandı'), ('REVISION_REQUIRED', 'Revizyon gerekli')], max_length=20)),
                ('feedback', models.TextField(blank=True, max_length=5000)),
                ('reviewed_at', models.DateTimeField(editable=False)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='capstone.capstoneacademicsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneAcademicSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=120, storage=capstone.storage.capstone_private_storage, upload_to=capstone.academic_models.academic_private_file_path)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='capstone.capstoneacademicsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapstoneAcademicSubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='capstone.capstoneacademicsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneAdvisorPrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_advisor_notes', to='capstone.capstoneproject')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='help_requests', to='capstone.capstoneproject')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneHelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='capstone.capstonehelprequest')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneHelpAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=120, storage=capstone.storage.capstone_private_storage, upload_to=capstone.academic_models.academic_private_file_path)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='capstone.capstonehelprequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapstoneLiteratureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=120, storage=capstone.storage.capstone_private_storage, upload_to=capstone.academic_models.academic_private_file_path)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='literature_versions', to='capstone.capstoneproject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneLiteratureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Onaylandı'), ('REVISION_REQUIRED', 'Revizyon gerekli')], max_length=20)),
                ('feedback', models.TextField(max_length=5000)),
                ('reviewed_at', models.DateTimeField(editable=False)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='capstone.capstoneliteratureversion')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneMeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('availability_note', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Talep edildi'), ('SCHEDULED', 'Planlandı'), ('HELD', 'Gerçekleşti'), ('CANCELLED', 'İptal edildi')], default='REQUESTED', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='capstone.capstoneproject')),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneMeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='note', to='capstone.capstonemeetingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CapstonePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bitirme Projesi Kontrol Planı', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_plans', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_plans', to='capstone.capstoneterm')),
            ],
        ),
        migrations.CreateModel(
            name='CapstonePlanCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('due_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='capstone.capstoneplan')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='capstonemeetingrequest',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_requests', to='capstone.capstoneplancheckpoint'),
        ),
        migrations.AddField(
            model_name='capstoneliteratureversion',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='literature_versions', to='capstone.capstoneplancheckpoint'),
        ),
        migrations.AddField(
            model_name='capstonehelprequest',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='help_requests', to='capstone.capstoneplancheckpoint'),
        ),
        migrations.CreateModel(
            name='CapstoneChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expectations', to='capstone.capstoneplancheckpoint')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CapstonePlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_plan_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneStudentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_due_at', models.DateTimeField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True)),
                ('extension_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capstone_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_progress', to='capstone.capstoneproject')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='capstone.capstoneplancheckpoint')),
                ('extension_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapstoneChecklistTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_ticks', to='capstone.capstonechecklistitem')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticks', to='capstone.capstonestudentcheckpoint')),
            ],
        ),
        migrations.AddField(
            model_name='capstoneacademicsubmission',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='capstone.capstonestudentcheckpoint'),
        ),
        migrations.CreateModel(
            name='CapstoneTemplateCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='capstone.capstoneplantemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneTemplateExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expectations', to='capstone.capstonetemplatecheckpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='capstoneplan',
            constraint=models.UniqueConstraint(fields=('term', 'advisor'), name='unique_capstone_advisor_term_plan'),
        ),
        migrations.AddConstraint(
            model_name='capstoneplancheckpoint',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_capstone_plan_checkpoint_order'),
        ),
        migrations.AddConstraint(
            model_name='capstoneliteratureversion',
            constraint=models.UniqueConstraint(fields=('capstone_project', 'version'), name='unique_capstone_literature_version'),
        ),
        migrations.AddConstraint(
            model_name='capstonechecklistitem',
            constraint=models.UniqueConstraint(fields=('checkpoint', 'order'), name='unique_capstone_expectation_order'),
        ),
        migrations.AddConstraint(
            model_name='capstonestudentcheckpoint',
            constraint=models.UniqueConstraint(fields=('capstone_project', 'checkpoint'), name='unique_capstone_student_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='capstonechecklisttick',
            constraint=models.UniqueConstraint(fields=('progress', 'item'), name='unique_capstone_student_expectation'),
        ),
        migrations.AddConstraint(
            model_name='capstoneacademicsubmission',
            constraint=models.UniqueConstraint(fields=('progress', 'attempt_number'), name='unique_capstone_academic_attempt'),
        ),
        migrations.AddConstraint(
            model_name='capstoneacademicsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='positive_capstone_academic_attempt'),
        ),
        migrations.AddConstraint(
            model_name='capstonetemplatecheckpoint',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_capstone_template_order'),
        ),
        migrations.RunPython(backfill_existing_advisors, guard_reverse_with_academic_data),
    ]
