# Generated by Django 5.2.17 on 2026-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_activate_existing_2026_fall'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstoneenrollment',
            name='eligibility_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capstoneenrollment',
            name='eligibility_override_reason',
            field=models.TextField(blank=True),
        ),
    ]
