# Generated by Django 5.2.1 on 2026-04-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Baslik')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('content', models.TextField(help_text='Dokumanin metin icerigi', verbose_name='Icerik')),
                ('category', models.CharField(choices=[('academic', 'Akademik'), ('internship', 'Staj'), ('course', 'Ders'), ('project', 'Proje'), ('general', 'Genel')], default='general', max_length=50, verbose_name='Kategori')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='knowledge/', verbose_name='Dosya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Olusturan')),
            ],
            options={
                'verbose_name': 'Bilgi Kaynagi',
                'verbose_name_plural': 'Bilgi Kaynaklari',
                'ordering': ['category', 'title'],
            },
        ),
    ]
