# Generated by Django 5.2.1 on 2026-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True, verbose_name='Soru')),
                ('question_hash', models.CharField(db_index=True, max_length=64, verbose_name='Soru Hash')),
                ('response', models.TextField(verbose_name='Cevap')),
                ('sources_used', models.JSONField(default=list, verbose_name='Kullanilan Kaynaklar')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Kullanim Sayisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Son Kullanim Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Chat Onbellek',
                'verbose_name_plural': 'Chat Onbellek',
                'ordering': ['-hit_count', '-last_used_at'],
            },
        ),
    ]
