# Generated by Django 5.2.1 on 2026-08-13 15:12

from django.db import migrations, models


def clear_legacy_ai_cache(apps, schema_editor):
    # Eski cache kayıtlarının hangi rolün kaynaklarıyla üretildiği bilinemez.
    apps.get_model('ai_assistant', 'ChatCache').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_chatcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(max_length=64, unique=True)),
                ('safe_summary', models.CharField(max_length=180)),
                ('ask_count', models.PositiveIntegerField(default=1)),
                ('roles', models.JSONField(blank=True, default=dict)),
                ('first_asked_at', models.DateTimeField(auto_now_add=True)),
                ('last_asked_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ask_count', '-last_asked_at'],
            },
        ),
        migrations.AddField(
            model_name='chatcache',
            name='audience_key',
            field=models.CharField(db_index=True, default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='audience',
            field=models.CharField(choices=[('all', 'Tüm giriş yapmış kullanıcılar'), ('student', 'Yalnızca öğrenciler'), ('teacher', 'Yalnızca akademisyenler'), ('alumni', 'Yalnızca mezunlar'), ('staff', 'Yalnızca yöneticiler')], db_index=True, default='all', max_length=12),
        ),
        migrations.RunPython(clear_legacy_ai_cache, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chatcache',
            name='question',
            field=models.TextField(verbose_name='Soru'),
        ),
        migrations.AddConstraint(
            model_name='chatcache',
            constraint=models.UniqueConstraint(fields=('question_hash', 'audience_key'), name='unique_ai_cache_audience'),
        ),
    ]
