# Generated by Django 5.2.1 on 2026-08-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('projects', '0019_projectcasestudy_future_developments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('contact_name', models.CharField(max_length=160, verbose_name='Yetkili adı ve soyadı')),
                ('organization', models.CharField(max_length=180, verbose_name='Şirket/kurum adı')),
                ('job_title', models.CharField(max_length=120, verbose_name='Görevi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Şirket web sitesi')),
                ('request_type', models.CharField(choices=[('internship', 'Stajyer arayışı'), ('recruitment', 'İşe alım'), ('team', 'Öğrenci/ekip arayışı'), ('project', 'Proje iş birliği'), ('capstone', 'Bitirme projesi önerisi'), ('research', 'Araştırma problemi'), ('sponsorship', 'Sponsorluk'), ('event', 'Etkinlik desteği'), ('speaker', 'Eğitim/konuşmacı talebi'), ('academic', 'Akademik iş birliği'), ('other', 'Diğer')], max_length=20, verbose_name='Talep türü')),
                ('interest_reference', models.CharField(blank=True, max_length=220, verbose_name='İlgilenilen proje veya öğrenci')),
                ('title', models.CharField(max_length=200, verbose_name='Talep başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('preferred_contact', models.CharField(choices=[('email', 'E-posta'), ('phone', 'Telefon'), ('video', 'Çevrim içi görüşme')], default='email', max_length=12, verbose_name='Tercih edilen iletişim yöntemi')),
                ('consent_accepted', models.BooleanField(default=False, verbose_name='KVKK ve iletişim onayı')),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_email', 'E-posta doğrulaması bekleniyor'), ('pending_review', 'Yönetici incelemesi bekleniyor'), ('approved', 'Onaylandı'), ('published', 'Yayımlandı'), ('rejected', 'Reddedildi')], db_index=True, default='pending_email', max_length=20)),
                ('publication_channel', models.CharField(choices=[('internal', 'Yalnızca iç değerlendirme'), ('project', 'Proje İlanları'), ('career', 'Kariyer'), ('event', 'Etkinlik yönetimi')], default='internal', max_length=12)),
                ('normalized_title', models.CharField(blank=True, max_length=200)),
                ('normalized_description', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True, verbose_name='Beklenen çıktı')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Son başvuru tarihi')),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='collaboration_requests', to='projects.projectcategory')),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_collaboration', to='career.opportunity')),
                ('project_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_collaboration', to='projects.projectrequest')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projecttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('technologies', models.ManyToManyField(blank=True, related_name='collaboration_requests', to='projects.technology')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='collab_status_date_idx')],
            },
        ),
    ]
